version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 8443:8443
      - 8082:8082
    volumes:
      - ./deployment/local/docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/var/www:cached
    links:
      - php-fpm
    depends_on:
      - php-fpm
    networks:
      - backend

  php-fpm:
    build: ./deployment/local/docker/php-fpm
    ports:
      - 8011:8011
    links:
      - postgres
    depends_on:
      - postgres
    volumes:
      - ./:/var/www:cached
    networks:
      - backend

  postgres:
    image: library/postgres:12.3
    restart: always
    volumes:
      - ./pg_data:/var/lib/postgresql/data:cached
    environment:
      - POSTGRES_PASSWORD=macdev
      - PGGSSENCMODE=disable
    ports:
      - 5432:5432
    networks:
      - backend

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - backend

networks:
  backend:


